[profile.default]
src = "src"
out = "out"
libs = ["../lib"]
test = "test"
script = "script"
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
ffi = false

[fmt]
line_length = 100
bracket_spacing = true
int_types = "long"
multiline_func_header = "params_first"
quote_style = "double"
number_underscore = "thousands"
wrap_comments = true
